name: Deploy MkDocs to GitHub Pages

on:
  # Triggers the workflow on push events to the main branch
  push:
    branches:
      - main

# Allows only one concurrent deployment, skipping runs queued between the most recent and latest
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # IMPORTANT: Needed to push the site files to the gh-pages branch

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Deploy MkDocs site
        run: mkdocs gh-deploy --force
