name: publish-github-pages

on:
  push:
    branches:
      - main
    paths:
      # This ensures the workflow only runs if files inside personal-website change
      - 'personal-website/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and Plugins
        run: pip install mkdocs mkdocs-material mkdocs-glightbox

      # We can remove the separate 'Build docs site' step.
      # The 'mkdocs gh-deploy' command automatically runs 'mkdocs build' first.

      - name: Deploy to GitHub Pages
        # The 'working-directory' tells the runner to execute the command from
        # inside the 'personal-website' folder, allowing mkdocs to find mkdocs.yml.
        run: mkdocs gh-deploy --force
        working-directory: personal-website
